server:
  port: 8080

spring:
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/wsk?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      #jsp 支持
      suffix: .jsp
      prefix: /jsp/

#整合Mybatis
mybatis:
#  扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: com.wutong.wsk.domain
#  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml
#  多层级目录  mapper-locations: classpath:mapper/**/**.xml
